import Navigation from '@/components/Navigation'
import Footer from '@/components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from '@/components/ProgressBarProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Assignment-module-12-blog',
  description: 'Generated by Indrajit Das',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="wrapper">
          <Navigation />
          <main className="content">
            <Providers>{children}</Providers>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
